# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Batcha < Formula
  desc "Declarative deployment tool for AWS Batch Job Definitions"
  homepage "https://github.com/kyosu-1/batcha"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyosu-1/batcha/releases/download/v0.2.2/batcha_0.2.2_darwin_amd64.tar.gz"
      sha256 "a0f3321a7960a5989a3778bca57f58676971d3bd7ea8db9b1b72f96b61280292"

      def install
        bin.install "batcha"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyosu-1/batcha/releases/download/v0.2.2/batcha_0.2.2_darwin_arm64.tar.gz"
      sha256 "91ebfb12a9a904dd2e3ada0ce705fd4bcad1282f9732e7830759bc2775d253f7"

      def install
        bin.install "batcha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyosu-1/batcha/releases/download/v0.2.2/batcha_0.2.2_linux_amd64.tar.gz"
      sha256 "21a066234eb2291b20d291efe1a01400f6253d43deb5d10a9fd28125202854ef"
      def install
        bin.install "batcha"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyosu-1/batcha/releases/download/v0.2.2/batcha_0.2.2_linux_arm64.tar.gz"
      sha256 "1d3320550e635a752ceeb93bfe5d60328acd28109c1bb5ae2ba9f13f700b2422"
      def install
        bin.install "batcha"
      end
    end
  end
end
