# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Batcha < Formula
  desc "Declarative deployment tool for AWS Batch Job Definitions"
  homepage "https://github.com/kyosu-1/batcha"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyosu-1/batcha/releases/download/v0.2.1/batcha_0.2.1_darwin_amd64.tar.gz"
      sha256 "e481e1d4ea2ea315b8e69c4eee7155e2f0e59924759bb55a97f25126cac0a007"

      def install
        bin.install "batcha"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyosu-1/batcha/releases/download/v0.2.1/batcha_0.2.1_darwin_arm64.tar.gz"
      sha256 "a4c183a8bd192aef749cb1c3ab6bd515df9f358c5e4976ca1455d5bbb2baf948"

      def install
        bin.install "batcha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyosu-1/batcha/releases/download/v0.2.1/batcha_0.2.1_linux_amd64.tar.gz"
      sha256 "b4885eddc6f917b67a60074bffde166a190b9751630531483355e9879a9268ea"
      def install
        bin.install "batcha"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyosu-1/batcha/releases/download/v0.2.1/batcha_0.2.1_linux_arm64.tar.gz"
      sha256 "4a8b75bccc79bf07716a270cde2e50a31560b795c5edc999dd868d4c9ec91c7f"
      def install
        bin.install "batcha"
      end
    end
  end
end
