# This file was generated by GoReleaser. DO NOT EDIT.
cask "batcha" do
  name "batcha"
  desc "Declarative deployment tool for AWS Batch Job Definitions"
  homepage "https://github.com/kyosu-1/batcha"
  version "0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "batcha"

  on_macos do
    on_intel do
      url "https://github.com/kyosu-1/batcha/releases/download/v#{version}/batcha_#{version}_darwin_amd64.tar.gz"
      sha256 "9f11cf90770f9d0bc8065bfad09cc7d04daba9e9b0d5f235f306d9814afe386f"
    end
    on_arm do
      url "https://github.com/kyosu-1/batcha/releases/download/v#{version}/batcha_#{version}_darwin_arm64.tar.gz"
      sha256 "e5f99390bcb542827172487f708ac4bdcbe1f81903e6c0b06205d0d8f8072170"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kyosu-1/batcha/releases/download/v#{version}/batcha_#{version}_linux_amd64.tar.gz"
      sha256 "543ddb97184dff23f7f98f06d6272c206d147677fbb689637a3229307bfb1cfe"
    end
    on_arm do
      url "https://github.com/kyosu-1/batcha/releases/download/v#{version}/batcha_#{version}_linux_arm64.tar.gz"
      sha256 "dc830b9492d8918f03fe372e0c9835069aa06ab4c0ce5b2ac342ea499e38aa6f"
    end
  end

  # No zap stanza required
end
