# This file was generated by GoReleaser. DO NOT EDIT.
cask "batcha" do
  name "batcha"
  desc "Declarative deployment tool for AWS Batch Job Definitions"
  homepage "https://github.com/kyosu-1/batcha"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "batcha"

  on_macos do
    on_intel do
      url "https://github.com/kyosu-1/batcha/releases/download/v#{version}/batcha_#{version}_darwin_amd64.tar.gz"
      sha256 "8f48d883446e93a46e10a78f48c4ce0c935f80fe3bc0ef5c4ab5e351e5c1a13c"
    end
    on_arm do
      url "https://github.com/kyosu-1/batcha/releases/download/v#{version}/batcha_#{version}_darwin_arm64.tar.gz"
      sha256 "a2ac3a76732232793c6d9623d37bdf5ed4a5be32a2945c8bdf10e38debf15609"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kyosu-1/batcha/releases/download/v#{version}/batcha_#{version}_linux_amd64.tar.gz"
      sha256 "c0409dff6f99a86b38db69bd36f6148d2a8745651bf8879fd950b5085ca6646c"
    end
    on_arm do
      url "https://github.com/kyosu-1/batcha/releases/download/v#{version}/batcha_#{version}_linux_arm64.tar.gz"
      sha256 "7903f3bbc0701d810bbc13281081d861867e1e9e9cc1bbdf780a9ca14c3b7560"
    end
  end

  # No zap stanza required
end
