# This file was generated by GoReleaser. DO NOT EDIT.
cask "isuenv" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "c1a7746c0e8115ee9e109557784a77a53addcb8c557db47fc01c23621623cf1e"
      url "https://github.com/kyosu-1/isuenv/releases/download/v#{version}/isuenv_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kyosu-1/isuenv/"
    end
    on_arm do
      sha256 "a1e9b4014d87c7456aa7252cf682ae1656d578f5872bc67f549624b941bd0919"
      url "https://github.com/kyosu-1/isuenv/releases/download/v#{version}/isuenv_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kyosu-1/isuenv/"
    end
  end

  on_linux do
    on_intel do
      sha256 "dae797117a076f7920d115fcef341d0c805190ecd467abb1df975141e8805073"
      url "https://github.com/kyosu-1/isuenv/releases/download/v#{version}/isuenv_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kyosu-1/isuenv/"
    end
    on_arm do
      sha256 "f7cc71fa90915e70e4b099008b89c383711153a35c6e1bc203e154698701310c"
      url "https://github.com/kyosu-1/isuenv/releases/download/v#{version}/isuenv_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kyosu-1/isuenv/"
    end
  end

  name "isuenv"
  desc "CLI to create and destroy ISUCON practice environments on AWS EC2"
  homepage "https://github.com/kyosu-1/isuenv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "isuenv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/isuenv"]
    end
  end

  # No zap stanza required

end
