# This file was generated by GoReleaser. DO NOT EDIT.
cask "isuenv" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "644f065c47fef939d677ea5d1a4362f18da28b908a479040c5c199cb2f3344a4"
      url "https://github.com/kyosu-1/isuenv/releases/download/v#{version}/isuenv_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kyosu-1/isuenv/"
    end
    on_arm do
      sha256 "ac6067de32367890714c6968691b6b13d6a3487b86126ea52df64faacb65cf0f"
      url "https://github.com/kyosu-1/isuenv/releases/download/v#{version}/isuenv_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kyosu-1/isuenv/"
    end
  end

  on_linux do
    on_intel do
      sha256 "03765a3ff19df1c83a61ea2022d147adcd877cfc36f928d54e20a42952bb05e4"
      url "https://github.com/kyosu-1/isuenv/releases/download/v#{version}/isuenv_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kyosu-1/isuenv/"
    end
    on_arm do
      sha256 "1da0fb44e5f731f22c9c365843e42a392aeb335adb9e34fbdf7469f5823cb72a"
      url "https://github.com/kyosu-1/isuenv/releases/download/v#{version}/isuenv_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kyosu-1/isuenv/"
    end
  end

  name "isuenv"
  desc "CLI to create and destroy ISUCON practice environments on AWS EC2"
  homepage "https://github.com/kyosu-1/isuenv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "isuenv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/isuenv"]
    end
  end

  # No zap stanza required

end
