# This file was generated by GoReleaser. DO NOT EDIT.
cask "isuenv" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "0cbcfcd63b8af0b5b477f0ef90312010b5a779707817d401b89dafbf7639bc0c"
      url "https://github.com/kyosu-1/isuenv/releases/download/v#{version}/isuenv_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kyosu-1/isuenv/"
    end
    on_arm do
      sha256 "8ca384d6a70de3f7de62bbbc6bea2512b2e80034e74efa2b39957ff1492074d0"
      url "https://github.com/kyosu-1/isuenv/releases/download/v#{version}/isuenv_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kyosu-1/isuenv/"
    end
  end

  on_linux do
    on_intel do
      sha256 "2b8851e079b59b628df3ca02bd45be9277827b5291510c7e8d51c9103a639134"
      url "https://github.com/kyosu-1/isuenv/releases/download/v#{version}/isuenv_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kyosu-1/isuenv/"
    end
    on_arm do
      sha256 "5de6a7714adda3e885d992bc420d55bba61a28ee11df735ac79a3b654c20a45b"
      url "https://github.com/kyosu-1/isuenv/releases/download/v#{version}/isuenv_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kyosu-1/isuenv/"
    end
  end

  name "isuenv"
  desc "CLI to create and destroy ISUCON practice environments on AWS EC2"
  homepage "https://github.com/kyosu-1/isuenv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "isuenv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/isuenv"]
    end
  end

  # No zap stanza required

end
