# This file was generated by GoReleaser. DO NOT EDIT.
cask "tetherd" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "30c6ecb9147b646a793ce59402b00403fbf41c40eec1372cc1336f122e8f9567"
      url "https://github.com/kyosu-1/tetherd/releases/download/v#{version}/tetherd_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "42edb50a69505b78453f6f84a7cc12c4b6524519c3e372fc84736327a12c43b2"
      url "https://github.com/kyosu-1/tetherd/releases/download/v#{version}/tetherd_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "tetherd"
  desc "mirrord-like local development environment for ECS Fargate"
  homepage "https://github.com/kyosu-1/tetherd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tetherd"
  binary "tetherd-helper"
  binary "tetherd-exec"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  uninstall launchctl: [
      "dev.tetherd.helper",
    ],
    delete: [
      "/Library/LaunchDaemons/dev.tetherd.helper.plist",
      "/usr/local/libexec/tetherd",
    ]

  # No zap stanza required

  caveats <<~EOS
    tetherd needs a root helper for pf, /etc/resolver and the tetherd group:

      sudo tetherd-helper install

    Then run `tetherd doctor`. It checks everything else this needs,
    including the SSM session-manager-plugin, which is not installed as a
    dependency because AWS's own installer puts it somewhere Homebrew
    cannot see.

    Run that again after every upgrade - it reinstalls both binaries into a
    root-owned directory and restarts the daemon.
  EOS
end
