# This file was generated by GoReleaser. DO NOT EDIT.
cask "tetherd" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "da222aac017a78bc613d1764d123ce150a22a0e0c0838096d4f8908f84665463"
      url "https://github.com/kyosu-1/tetherd/releases/download/v#{version}/tetherd_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cb4f3bd2f0b940605f860ac9dc82c3aa91055fab7a5699e810d2a09416c1415f"
      url "https://github.com/kyosu-1/tetherd/releases/download/v#{version}/tetherd_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "tetherd"
  desc "mirrord-like local development environment for ECS Fargate"
  homepage "https://github.com/kyosu-1/tetherd"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "session-manager-plugin",
    ]

  binary "tetherd"
  binary "tetherd-helper"
  binary "tetherd-exec"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path]
  end

  uninstall launchctl: [
      "dev.tetherd.helper",
    ],
    delete: [
      "/Library/LaunchDaemons/dev.tetherd.helper.plist",
      "/usr/local/libexec/tetherd",
    ]

  # No zap stanza required

  caveats <<~EOS
    tetherd needs a root helper for pf, /etc/resolver and the tetherd group:

      sudo tetherd-helper install

    Run that again after every upgrade - it reinstalls both binaries into a
    root-owned directory and restarts the daemon.
  EOS
end
